---
# Source: wallet-bc-redirect/templates/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate-name }}
  namespace: develop
spec:
  secretName: { { .Values.secret-certificate-name } }
  issuerRef:
    kind: Issuer
    name: letsencrypt-prod
  commonName: {{ .Values.certificate-domain }}
  dnsNames:
    - {{ .Values.certificate-domain }}
---